import re

with open("src/coreason_manifest/spec/ontology.py", "r") as f:
    content = f.read()

# Fix docstring 1
content = content.replace(
    '"""AGENT INSTRUCTION: A declarative neural intent representing probabilistic schema induction. The LLM evaluates a micro-batch of intercepted, obfuscated data and projects it into a strict StateContract."""',
    '"""AGENT INSTRUCTION: A declarative neural intent representing probabilistic schema induction.\n    The LLM evaluates a micro-batch of intercepted, obfuscated data and projects it into a strict StateContract."""'
)

# Fix field description 1
content = content.replace(
    'description="Optional mapping generated by the LLM, such as a JSONata query, to physically transform the raw intercept into the inferred schema"',
    'description="Optional mapping generated by the LLM, such as a JSONata query, "\n        "to physically transform the raw intercept into the inferred schema"'
)

# Fix docstring 2
content = content.replace(
    '"""AGENT INSTRUCTION: A deterministic physical actuator representing a headless wiretap on the browser/OS network layer (e.g., CDP Network.responseReceived or eBPF socket trace)."""',
    '"""AGENT INSTRUCTION: A deterministic physical actuator representing a headless wiretap on the browser/OS network layer\n    (e.g., CDP Network.responseReceived or eBPF socket trace)."""'
)

# Fix docstring 3
content = content.replace(
    '"""AGENT INSTRUCTION: A deterministic physical actuator representing a raw pointer read from an OS-level heap or WebAssembly linear memory matrix."""',
    '"""AGENT INSTRUCTION: A deterministic physical actuator representing a raw pointer read from an OS-level heap\n    or WebAssembly linear memory matrix."""'
)

with open("src/coreason_manifest/spec/ontology.py", "w") as f:
    f.write(content)
