site_name: CoReason Manifest
site_url: https://coreason-ai.github.io/coreason_manifest/
repo_name: CoReason-AI/coreason_manifest
repo_url: https://github.com/CoReason-AI/coreason_manifest

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - toc.integrate
    - search.suggest
    - search.highlight

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src/]
          options:
            docstring_style: null
            show_root_heading: true
            show_bases: true
            show_signature_annotations: true
  - mike
  - minify
  - git-revision-date-localized

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets
