with open("src/coreason_manifest/spec/ontology.py", "r") as f:
    content = f.read()

new_class = """
class SchemaInferenceIntent(CoreasonBaseState):
    \"\"\"AGENT INSTRUCTION: A declarative neural intent representing probabilistic schema induction. The LLM evaluates a micro-batch of intercepted, obfuscated data and projects it into a strict StateContract.\"\"\"

    type: Literal["schema_inference"] = Field(default="schema_inference")
    source_capture_id: str = Field(min_length=1, max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")
    sampled_micro_batch: list[JsonPrimitiveState] = Field(description="The isolated safe slice of the payload")
    inferred_schema_contract: StateContract = Field(description="The resulting rigid schema the LLM believes governs the data")
    compiled_extraction_routine: DeterministicExtractionContract | None = Field(default=None, description="Optional mapping generated by the LLM, such as a JSONata query, to physically transform the raw intercept into the inferred schema")

    @field_validator("sampled_micro_batch", mode="before")
    @classmethod
    def validate_payload(cls, v: Any) -> Any:
        return _validate_payload_bounds(v)

    @model_validator(mode="after")
    def sort_arrays(self) -> Self:
        object.__setattr__(self, "sampled_micro_batch", sorted(self.sampled_micro_batch, key=lambda x: str(x)))
        return self
"""

target = "type AnyPresentationIntent = Annotated["
if target in content and "class SchemaInferenceIntent" not in content:
    content = content.replace(target, new_class + "\n\n" + target)

with open("src/coreason_manifest/spec/ontology.py", "w") as f:
    f.write(content)
print("Patched SchemaInferenceIntent")
