with open("src/coreason_manifest/spec/ontology.py") as f:
    content = f.read()

# Insert before AnyStateEvent (around line 13535)
insert_marker = "type AnyStateEvent = Annotated["

new_code = """class EpistemicZeroTrustReceipt(CoreasonBaseState):
    \"\"\"
    AGENT INSTRUCTION: A cryptographically frozen historical fact proving the flawless execution of an EpistemicZeroTrustContract.

    CAUSAL AFFORDANCE: Permits the orchestrator to append the transmuted payload to the global immutable ledger, certifying that prompt injection was structurally impossible and AST contracts were fulfilled.

    EPISTEMIC BOUNDS: `firewall_breach_detected` must strictly be False. Hashes are bounded to RFC 8785 canonicalization requirements.

    MCP ROUTING TRIGGERS: Cryptographic Ledger, Formal Verification Receipt, Immutable Provenance, Hash Canonicalization, Data Masking
    \"\"\"
    event_cid: Annotated[str, StringConstraints(min_length=1, max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = Field(
        description="A Content Identifier (CID) acting as a cryptographic Lineage Watermark binding this node to the Merkle-DAG.",
    )
    prior_event_hash: Annotated[str, StringConstraints(min_length=1, max_length=128, pattern="^[a-f0-9]{64}$")] | None = Field(
        default=None,
        description="The SHA-256 hash of the temporally preceding event, establishing the Merkle-DAG chain.",
    )
    timestamp: float = Field(
        ge=0.0,
        le=253402300799.0,
        description="Causal Ancestry markers required to resolve decentralized event ordering.",
    )
    topology_class: Literal["zero_trust_receipt"] = Field(
        default="zero_trust_receipt", description="Discriminator for a zero-trust receipt."
    )
    intent_reference_id: Annotated[str, StringConstraints(min_length=1, max_length=128, pattern="^[a-zA-Z0-9_.:-]+$")] = Field(
        description="Pointer to the originating EpistemicZeroTrustContract."
    )
    llm_blind_plan_hash: Annotated[str, StringConstraints(min_length=1, max_length=128, pattern="^[a-f0-9]{64}$")] = Field(
        description="RFC 8785 hash of the proxy-only structural logic generated by the LLM."
    )
    firewall_breach_detected: Literal[False] = Field(
        default=False,
        description="A strictly False literal guaranteeing no raw entropy leaked into the LLM context."
    )
    remediation_epochs_consumed: int = Field(
        ge=0,
        le=10,
        description="The exact count of DbC retries required."
    )
    transmuted_payload_hash: Annotated[str, StringConstraints(min_length=1, max_length=128, pattern="^[a-f0-9]{64}$")] = Field(
        description="RFC 8785 canonical hash of the final executed payload."
    )

    @model_validator(mode='after')
    def verify_firewall_integrity(self) -> Self:
        \"\"\"Topological boundary: Ensures the CI/CD pipeline and runtime physically cannot instantiate a receipt if the OpenSymbolicAI firewall failed.\"\"\"
        if self.firewall_breach_detected is not False:
            raise ValueError("Topological Collapse: Firewall breach detected. Receipt invalid.")
        return self


"""

content = content.replace(insert_marker, new_code + insert_marker)

with open("src/coreason_manifest/spec/ontology.py", "w") as f:
    f.write(content)
