[project]
site_name = "CoReason Manifest"
site_url = "https://coreason-ai.github.io/coreason_manifest/"
repo_name = "CoReason-AI/coreason_manifest"
repo_url = "https://github.com/CoReason-AI/coreason_manifest"

features = [
    "navigation.instant",
    "navigation.tracking",
    "navigation.tabs",
    "toc.integrate",
    "search.highlight"
]

[project.plugins.mkdocstrings.handlers.python]
paths = ["src/"]

[project.plugins.mkdocstrings.handlers.python.options]
show_root_heading = true
show_bases = true
show_signature_annotations = true

[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.tabbed]

[project.markdown_extensions.pymdownx.snippets]