[project]
site_name = "CoReason Manifest"
site_url = "https://coreason-ai.github.io/coreason_manifest/"
repo_name = "CoReason-AI/coreason_manifest"
repo_url = "https://github.com/CoReason-AI/coreason_manifest"

[project.theme]
features = [
    "navigation.instant",
    "navigation.tracking",
    "navigation.tabs",
    "toc.integrate",
    "search.highlight"
]

[project.plugins.search]

[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.tabbed]

[project.markdown_extensions.pymdownx.snippets]
