# Copyright (c) 2025 CoReason, Inc.. All Rights Reserved
#
# This software is licensed under the Prosperity Public License 3.0.0.
# The issuer of the Prosperity Public License for this software is CoReason, Inc..
#
# For a commercial version of this software, please contact us at gowtham.rao@coreason.ai.

from typing import Literal

from pydantic import Field

from coreason_manifest.core.base import CoreasonBaseModel

type QoSClassification = Literal["critical", "high", "interactive", "background_batch"]


class RateCard(CoreasonBaseModel):
    """
    Economic constraints for liquid compute operations.
    """

    cost_per_million_input_tokens: float = Field(
        description="The cost per 1 million input tokens provided to the model."
    )
    cost_per_million_output_tokens: float = Field(
        description="The cost per 1 million output tokens generated by the model."
    )
    currency: str = Field(description="The currency of the associated costs.")


class ModelProfile(CoreasonBaseModel):
    """
    Abstraction for an underlying LLM provider in liquid compute.
    """

    model_name: str = Field(description="The identifier of the underlying model.")
    provider: str = Field(description="The name of the provider hosting the model.")
    context_window_size: int = Field(description="The maximum context window size in tokens.")
    capabilities: list[str] = Field(description="A list of supported capabilities by the model.")
    rate_card: RateCard = Field(description="The economic cost definition associated with the model.")


class ComputeProvisioningRequest(CoreasonBaseModel):
    """
    A request by a swarm to provision resources based on requirements.
    """

    max_budget: float = Field(description="The maximum cost budget allowable for the provisioned compute.")
    required_capabilities: list[str] = Field(
        description="The minimal functional capabilities required by the requested compute."
    )
    qos_class: QoSClassification = Field(
        default="interactive",
        description="The Quality of Service priority, used by the compute spot market for semantic load shedding.",
    )
