# Copyright (c) 2025 CoReason, Inc.. All Rights Reserved
#
# This software is licensed under the Prosperity Public License 3.0.0.
# The issuer of the Prosperity Public License for this software is CoReason, Inc..
#
# For a commercial version of this software, please contact us at gowtham.rao@coreason.ai.

"""AGENT INSTRUCTION: This file defines model profiles, provisioning requests, and rate cards for cognitive
compute routing. This is a STRICTLY KINETIC BOUNDARY. These schemas orchestrate probabilistic boundaries, raw
GPU tensor constraints, and dynamic kinetic dispatch. DO NOT inject persistent state-saving, relational
database structures, or upstream workflow logic here. All attributes must be strictly mapped to continuous
hardware constraints and tensor environments.
"""

from typing import Literal

from pydantic import Field

from coreason_manifest.core.base import CoreasonBaseModel

type QoSClassification = Literal["critical", "high", "interactive", "background_batch"]


class RoutingFrontier(CoreasonBaseModel):
    """
    Mathematical Pareto boundaries for dynamic spot-market liquid compute.
    """

    max_latency_ms: int = Field(
        gt=0, description="The absolute physical speed limit acceptable for time-to-first-token or total generation."
    )
    max_cost_microcents_per_token: int = Field(
        gt=0, description="The strict magnitude ceiling. MUST be an integer to maintain cryptographic determinism."
    )
    min_capability_score: float = Field(
        ge=0.0, le=1.0, description="The cognitive capability floor required for the task (0.0 to 1.0)."
    )
    tradeoff_preference: Literal[
        "latency_optimized", "cost_optimized", "capability_optimized", "carbon_optimized", "balanced"
    ] = Field(description="The mathematical optimization vector to break ties within the frontier.")
    max_carbon_intensity_gco2eq_kwh: float | None = Field(
        default=None,
        ge=0.0,
        description=(
            "The maximum operational carbon intensity of the physical data center "
            "grid allowed for this agent's routing."
        ),
    )


class RateCard(CoreasonBaseModel):
    """
    Economic constraints for liquid compute operations.
    """

    cost_per_million_input_tokens: float = Field(
        description="The cost per 1 million input tokens provided to the model."
    )
    cost_per_million_output_tokens: float = Field(
        description="The cost per 1 million output tokens generated by the model."
    )
    currency: str = Field(description="The currency of the associated costs.")


class ModelProfile(CoreasonBaseModel):
    """
    Abstraction for an underlying LLM provider in liquid compute.
    """

    model_name: str = Field(description="The identifier of the underlying model.")
    provider: str = Field(description="The name of the provider hosting the model.")
    context_window_size: int = Field(description="The maximum context window size in tokens.")
    capabilities: list[str] = Field(description="A list of supported capabilities by the model.")
    rate_card: RateCard = Field(description="The economic cost definition associated with the model.")
    supported_functional_experts: list[str] = Field(
        default_factory=list,
        description="A declarative list of specialized functional expert clusters (e.g., 'falsifier', 'synthesizer') "
        "physically present in this model's architecture.",
    )


class ComputeProvisioningRequest(CoreasonBaseModel):
    """
    A request by a swarm to provision resources based on requirements.
    """

    max_budget: float = Field(description="The maximum cost budget allowable for the provisioned compute.")
    required_capabilities: list[str] = Field(
        description="The minimal functional capabilities required by the requested compute."
    )
    qos_class: QoSClassification = Field(
        default="interactive",
        description="The Quality of Service priority, used by the compute spot market for semantic load shedding.",
    )
