# Copyright (c) 2025 CoReason, Inc.. All Rights Reserved
#
# This software is licensed under the Prosperity Public License 3.0.0.
# The issuer of the Prosperity Public License for this software is CoReason, Inc..
#
# For a commercial version of this software, please contact us at gowtham.rao@coreason.ai.

"""AGENT INSTRUCTION: This file maps the Neurosymbolic Handoff and dynamic symbolic validation configurations.
This is a STRICTLY KINETIC BOUNDARY. These schemas represent friction, hardware limits, and physical
execution. This boundary governs probabilistic tensor logic, VRAM geometries, and exogenous spatial actuation.
"""

from typing import Any, Literal

from pydantic import Field

from coreason_manifest.core.base import CoreasonBaseModel


class NeuroSymbolicHandoff(CoreasonBaseModel):
    handoff_id: str = Field(
        min_length=1,
        description="A Content Identifier (CID) acting as a cryptographic Lineage Watermark "
        "for this symbolic delegation.",
    )
    solver_protocol: Literal["z3", "lean4", "coq", "tla_plus", "sympy"] = Field(
        description="The target Deterministic Solver for the Neurosymbolic Handoff."
    )
    formal_grammar_payload: str = Field(
        description="The raw code or formal proof syntax generated by the LLM as translation matrices "
        "between neural and deterministic space."
    )
    expected_proof_schema: dict[str, Any] = Field(
        description=(
            "The strict JSON Schema the deterministic solver must use to return the verified answer to the agent."
        )
    )
    timeout_ms: int = Field(
        gt=0,
        description="The Formal Verification Bounds time limit allocated to the symbolic solver before aborting.",
    )
