# Copyright (c) 2025 CoReason, Inc.. All Rights Reserved
#
# This software is licensed under the Prosperity Public License 3.0.0.
# The issuer of the Prosperity Public License for this software is CoReason, Inc..
#
# For a commercial version of this software, please contact us at gowtham.rao@coreason.ai.

from typing import Any, Literal

from pydantic import Field

from coreason_manifest.core.base import CoreasonBaseModel


class NeuroSymbolicHandoff(CoreasonBaseModel):
    handoff_id: str = Field(min_length=1, description="Unique identifier for this symbolic delegation.")
    solver_protocol: Literal["z3", "lean4", "coq", "tla_plus", "sympy"] = Field(
        description="The target deterministic math/logic engine."
    )
    formal_grammar_payload: str = Field(
        description="The raw code or formal proof syntax generated by the LLM to be evaluated."
    )
    expected_proof_schema: dict[str, Any] = Field(
        description=(
            "The strict JSON Schema the deterministic solver must use to return the verified answer to the agent."
        )
    )
    timeout_ms: int = Field(
        gt=0,
        description="The maximum compute time allocated to the symbolic solver before aborting.",
    )
