import pytest
from hypothesis import given
from hypothesis import strategies as st
from pydantic import ValidationError

from coreason_manifest.spec.domains.scientific_vis import (
    FunctionalModule,
    GraphicElement,
    HierarchicalBlueprint,
    InterModuleConnection,
    SciVisIntent,
    SpatialCorrection,
    VectorRenderPayload,
    VisInformationType,
    VisualCriticFeedback,
)
from coreason_manifest.spec.domains.scivis_templates import ComponentTemplate, TemplateOverride


@st.composite
def template_override_strategy(draw: st.DrawFn) -> TemplateOverride:
    from coreason_manifest.spec.domains.scivis_style import ColorToken

    return TemplateOverride(
        target_internal_id=draw(st.text(min_size=1)),
        new_label=draw(st.one_of(st.none(), st.text())),
        new_color_token=draw(st.one_of(st.none(), st.sampled_from(list(ColorToken)))),
        is_hidden=draw(st.booleans()),
    )


@st.composite
def component_template_strategy(draw: st.DrawFn) -> ComponentTemplate:
    urn = draw(
        st.builds(
            lambda a, b, c: f"urn:sci-design:{a}:{b}:v{c}",
            st.text(alphabet="abcdefghijklmnopqrstuvwxyz0123456789-", min_size=1),
            st.text(alphabet="abcdefghijklmnopqrstuvwxyz0123456789-", min_size=1),
            st.integers(min_value=0, max_value=999),
        )
    )
    overrides = draw(st.lists(template_override_strategy(), max_size=5))
    return ComponentTemplate(urn=urn, overrides=overrides)


@st.composite
def graphic_element_strategy(draw: st.DrawFn) -> GraphicElement:
    return GraphicElement(
        id=draw(st.text(min_size=1)),
        semantic_role=draw(st.text()),
        proposed_shape=draw(st.sampled_from(["rectangle", "cylinder", "document", "none"])),
    )


@st.composite
def functional_module_strategy(draw: st.DrawFn) -> FunctionalModule:
    return FunctionalModule(
        module_id=draw(st.text(min_size=1)),
        title=draw(st.text()),
        elements=draw(st.lists(graphic_element_strategy(), max_size=5)),
        template_reference=draw(st.one_of(st.none(), component_template_strategy())),
    )


@st.composite
def valid_hierarchical_blueprint_strategy(draw: st.DrawFn) -> HierarchicalBlueprint:
    modules = draw(st.lists(functional_module_strategy(), min_size=1, max_size=5))
    module_ids = [m.module_id for m in modules]

    connections = draw(
        st.lists(
            st.builds(
                InterModuleConnection,
                source_module_id=st.sampled_from(module_ids),
                target_module_id=st.sampled_from(module_ids),
                label=st.one_of(st.none(), st.text()),
                flow_type=st.sampled_from(["sequential", "feedback", "bidirectional"]),
                source_port=st.one_of(st.none(), st.text(min_size=1)),
                target_port=st.one_of(st.none(), st.text(min_size=1)),
            ),
            max_size=5,
        )
    )

    return HierarchicalBlueprint(
        modules=modules,
        connections=connections,
        aspect_ratio_preference=draw(st.sampled_from(["16:9", "4:3", "1:1"])),
    )


@given(valid_hierarchical_blueprint_strategy())
def test_valid_hierarchical_blueprint(blueprint: HierarchicalBlueprint) -> None:
    # If the blueprint is generated by the strategy, it should pass validation implicitly
    assert isinstance(blueprint, HierarchicalBlueprint)


def test_invalid_hierarchical_blueprint_source() -> None:
    modules = [
        FunctionalModule(module_id="mod1", title="Module 1", elements=[]),
        FunctionalModule(module_id="mod2", title="Module 2", elements=[]),
    ]
    connections = [
        InterModuleConnection(
            source_module_id="invalid_mod",
            target_module_id="mod2",
            label="conn",
            flow_type="sequential",
        )
    ]

    with pytest.raises(ValidationError) as exc_info:
        HierarchicalBlueprint(modules=modules, connections=connections, aspect_ratio_preference="16:9")

    assert 'Module ID "invalid_mod" does not exist in the declared modules list.' in str(exc_info.value)


def test_invalid_hierarchical_blueprint_target() -> None:
    modules = [
        FunctionalModule(module_id="mod1", title="Module 1", elements=[]),
    ]
    connections = [
        InterModuleConnection(
            source_module_id="mod1",
            target_module_id="invalid_target",
            label="conn",
            flow_type="sequential",
        )
    ]

    with pytest.raises(ValidationError) as exc_info:
        HierarchicalBlueprint(modules=modules, connections=connections, aspect_ratio_preference="16:9")

    assert 'Module ID "invalid_target" does not exist in the declared modules list.' in str(exc_info.value)


def test_scivis_intent() -> None:
    intent = SciVisIntent(
        vis_type=VisInformationType.QUALITATIVE_SCHEMATIC,
        requires_code_execution=False,
        requires_vector_layout=True,
    )
    assert intent.vis_type == VisInformationType.QUALITATIVE_SCHEMATIC


def test_spatial_correction() -> None:
    correction = SpatialCorrection(
        target_element_id="elem1",
        issue="overlap",
        suggested_action="move right",
    )
    assert correction.issue == "overlap"


def test_visual_critic_feedback() -> None:
    feedback = VisualCriticFeedback(
        is_publication_ready=False,
        hallucinated_elements=["fake_node"],
        missing_required_elements=[],
        readability_issues=["too small text"],
        spatial_corrections=[
            SpatialCorrection(
                target_element_id="elem1",
                issue="overlap",
                suggested_action="move right",
            )
        ],
        global_aesthetic_score=8.5,
    )
    assert feedback.global_aesthetic_score == 8.5


def test_vector_render_payload() -> None:
    payload = VectorRenderPayload(
        format="svg",
        source_code="<svg></svg>",
        interaction_steps=1,
    )
    assert payload.format == "svg"
    assert payload.raster_preview_url is None


def test_data_artifact_element():
    from coreason_manifest.spec.domains.scientific_vis import DataArtifactElement

    element = DataArtifactElement(
        id="ele-001",
        semantic_role="distribution_scatter_plot",
        artifact_uri="s3://data/artifacts/scatter.svg",
        maintain_aspect_ratio=True,
    )
    assert element.id == "ele-001"
    assert element.semantic_role == "distribution_scatter_plot"
    assert element.artifact_uri == "s3://data/artifacts/scatter.svg"
    assert element.maintain_aspect_ratio is True
