# Copyright (c) 2025 CoReason, Inc.
#
# This software is proprietary and dual-licensed.
# Licensed under the Prosperity Public License 3.0 (the "License").
# A copy of the license is available at https://prosperitylicense.com/versions/3.0.0
# For details, see the LICENSE file.
# Commercial use beyond a 30-day trial requires a separate license.
#
# Source Code: https://github.com/CoReason-AI/coreason-manifest

from enum import Enum

from pydantic import BaseModel, Field


class SpatialRelation(str, Enum):  # noqa: UP042
    """
    Strict vocabulary for spatial relationships in the Declarative Spatial AST.
    """

    LEFT_OF = "LEFT_OF"
    RIGHT_OF = "RIGHT_OF"
    ABOVE = "ABOVE"
    BELOW = "BELOW"
    INSIDE = "INSIDE"
    OUTSIDE = "OUTSIDE"


class LayoutDirection(str, Enum):  # noqa: UP042
    """
    Strict vocabulary for primary flow direction in the Declarative Spatial AST.
    """

    TOP_TO_BOTTOM = "TOP_TO_BOTTOM"
    LEFT_TO_RIGHT = "LEFT_TO_RIGHT"
    RADIAL = "RADIAL"
    GRID = "GRID"
    SNAKE = "SNAKE"


class RoutingAlgorithm(str, Enum):  # noqa: UP042
    """
    Strict vocabulary for edge routing algorithms.
    """

    ORTHOGONAL = "ORTHOGONAL"
    SPLINE = "SPLINE"
    DIRECT = "DIRECT"
    MANHATTAN = "MANHATTAN"


class Point2D(BaseModel):
    """
    A 2D point.
    """

    x: float
    y: float


class PaddingConfig(BaseModel):
    """
    Padding configuration for bounding boxes.
    """

    top: float
    right: float
    bottom: float
    left: float


class BoundingBox(BaseModel):
    """
    A 2D bounding box definition.
    Allows negative coordinates since canvas origins vary.
    """

    x: float
    y: float
    width: float = Field(ge=0)
    height: float = Field(ge=0)
    padding: PaddingConfig | None = None


class RelativeConstraint(BaseModel):
    """
    Logical constraint building block of the AST.
    """

    target_id: str = Field(description="The node being placed")
    relation: SpatialRelation
    anchor_id: str = Field(description="The reference node")
    offset_mm: float | None = Field(default=None, description="Optional explicit distance in millimeters")


class SpatialLayoutBlueprint(BaseModel):
    """
    The master contract for the Declarative Spatial AST.
    Serves as the handoff payload between the LLM and the layout solver.
    """

    primary_direction: LayoutDirection
    fallback_directions: list[LayoutDirection] = Field(
        default=[],
        description="Allows solver to reflow if column width is exceeded",
    )
    edge_routing: RoutingAlgorithm
    constraints: list[RelativeConstraint] = Field(default=[], description="The AST generated by the AI")
    calculated_bounds: dict[str, BoundingBox] | None = Field(
        default=None,
        description="Where the downstream solver writes final math. Maps module_id to box.",
    )
