from pydantic import BaseModel, Field


class DataArtifactElement(BaseModel):
    id: str
    semantic_role: str = Field(description="e.g., 'distribution_scatter_plot' or 'results_bar_chart'")
    artifact_uri: str = Field(
        ..., description="The state-safe pointer to the executed Naked SVG generated by the data agent."
    )
    maintain_aspect_ratio: bool = Field(
        default=True, description="Crucial for plots where stretching axes invalidates the mathematical geometry."
    )
