# Copyright (c) 2025 CoReason, Inc.. All Rights Reserved
#
# This software is licensed under the Prosperity Public License 3.0.0.
# The issuer of the Prosperity Public License for this software is CoReason, Inc..
#
# For a commercial version of this software, please contact us at gowtham.rao@coreason.ai.

import hashlib
import json
from typing import Any, Self

from pydantic import Field, model_validator

from coreason_manifest.core.base import CoreasonBaseModel
from coreason_manifest.core.primitives import GitSHA
from coreason_manifest.telemetry.schemas import PrivacySentinel


class CustodyRecord(CoreasonBaseModel):
    """
    Cryptographic state of an agent to ensure full traceability and provenance.
    """

    prompt_template_sha: GitSHA = Field(description="The cryptographic SHA of the prompt template used.")
    context_hash: str = Field(description="The cryptographic hash of the input context provided to the agent.")
    temperature: float = Field(description="The temperature parameter used for generating the response.")


class ExecutionNode(CoreasonBaseModel):
    """
    Cryptographic state of an execution node in a Merkle DAG trace.
    """

    request_id: str = Field(description="The unique ID for this specific execution.")
    parent_request_id: str | None = Field(default=None, description="The ID of the parent request.")
    root_request_id: str | None = Field(default=None, description="The ID of the trace root.")

    inputs: PrivacySentinel = Field(description="The inputs provided to the execution node.")
    outputs: PrivacySentinel = Field(description="The outputs generated by the execution node.")
    parent_hashes: list[str] = Field(
        default_factory=list, description="A list of cryptographic hashes of parent execution nodes."
    )
    node_hash: str | None = Field(default=None, description="The cryptographic SHA-256 hash of this node.")

    @model_validator(mode="after")
    def validate_lineage(self) -> Self:
        if self.parent_request_id is not None and self.root_request_id is None:
            raise ValueError("Orphaned Lineage: parent_request_id is set but root_request_id is None")
        return self

    def generate_node_hash(self) -> str:
        """
        Generate a strictly deterministic SHA-256 hash for the node via RFC 8785 canonicalization.
        Ensures identical hashes across varying architectures and thread-states (NoGIL).
        """
        payload = {
            "request_id": self.request_id,
            "parent_request_id": self.parent_request_id,
            "root_request_id": self.root_request_id,
            "inputs": self.inputs,
            "outputs": self.outputs,
            "parent_hashes": self.parent_hashes,
        }

        def _canonicalize(obj: Any) -> Any:
            if isinstance(obj, dict):
                return {k: _canonicalize(v) for k, v in sorted(obj.items()) if v is not None}
            if isinstance(obj, list):
                return [_canonicalize(v) for v in obj]
            if isinstance(obj, tuple):
                return tuple([_canonicalize(v) for v in obj])
            if isinstance(obj, set):
                return sorted(
                    [_canonicalize(v) for v in obj if v is not None],
                    key=lambda x: json.dumps(x, sort_keys=True),
                )
            return obj

        canonical_payload = _canonicalize(payload)
        json_bytes = json.dumps(
            canonical_payload,
            ensure_ascii=False,
            separators=(",", ":"),
            sort_keys=True,
        ).encode("utf-8")
        return hashlib.sha256(json_bytes).hexdigest()

    @model_validator(mode="after")
    def populate_hash(self) -> Self:
        """Automatically populate node_hash if not explicitly provided."""
        if not self.node_hash:
            # Pydantic V2 frozen models workaround for updating fields post-validation.
            object.__setattr__(self, "node_hash", self.generate_node_hash())
        return self


class TamperError(ValueError):
    """Raised when an execution trace has been tampered with or is topologically invalid."""


def verify_merkle_proof(trace: list[ExecutionNode]) -> bool:
    """
    Verifies a Merkle DAG trace of execution nodes.
    Ensures that every node's hash is computationally valid and mathematically
    sound (matching canonical inputs/outputs) and topologically links correctly
    via Kahn's concept of parent hashes regardless of the temporal array index order.

    Returns True if validation succeeds, False otherwise.
    """
    # 1. Map all nodes by their asserted hash.
    node_map: dict[str, ExecutionNode] = {}
    for node in trace:
        if node.node_hash is None:
            return False
        node_map[node.node_hash] = node

    # 2. Verify computational integrity and topological links
    for node in trace:
        # Recompute to check for tampering
        if node.generate_node_hash() != node.node_hash:
            return False

        # Verify parent links
        for parent_hash in node.parent_hashes:
            if parent_hash not in node_map:
                return False

    return True
